Repository chaekggoji/FE, pull requests merged in 2025-04, with the labels that each got.

#59 🎈 구절 나눠요, 스터디원 관리 페이지 초기 기능 구현
  src/components/modules/board/Board.jsx
  src/components/modules/phrase/PhraseItem.jsx
  src/components/modules/phrase/PhraseWrite.jsx
  src/components/modules/post/CommentItem.jsx
  src/components/modules/post/PostDetail.jsx
  src/components/modules/post/PostEdit.jsx
  src/components/modules/post/PostWrite.jsx
  src/components/pages/study/detail/StudyInfo.jsx
  src/components/pages/study/detail/StudyMemberListItem.jsx
  src/pages/study/detail/Index.jsx
  src/pages/study/detail/Manage.jsx
  src/pages/study/detail/Phrases.jsx
  src/pages/study/detail/StudyDetailLayout.jsx
  src/queries/phrases/deletePhrase.js
  src/queries/phrases/getPhraseList.js
  src/queries/phrases/index.js
  src/queries/phrases/writePhrase.js
  src/queries/posts/deleteComment.js
  src/queries/study/deleteStudyMember.js
  src/queries/study/getStudyById.js
  src/queries/study/getStudyMemberList.js
  src/queries/study/joinStudy.js
  src/routes/ProtectedRoute.jsx
  src/store/useUserStore.js
Labels: enhancement(개선 요청), P1

#61 🌱 게시판 페이지네이션 구현
  src/components/common/Pagination.jsx
  src/components/modules/board/Board.jsx
  src/components/modules/phrase/PhraseItem.jsx
  src/components/modules/phrase/PhraseWrite.jsx
  src/components/pages/study/detail/StudyInfo.jsx
  src/hooks/usePagination.jsx
  src/main.jsx
  src/pages/study/detail/Index.jsx
  src/pages/study/detail/Manage.jsx
  src/pages/study/detail/Phrases.jsx
  src/pages/study/detail/StudyDetailLayout.jsx
  src/queries/phrases/index.js
  src/queries/posts/getPostListByType.js
  src/queries/study/index.js
Labels: enhancement(개선 요청), P1

#62 ✍️ 스터디 생성 페이지 기능 구현 완료
  src/assets/icons/icon_check_black_24.svg
  src/components/common/CustomInputField.jsx
  src/components/common/CustomTextarea.jsx
  src/components/common/InputError.jsx
  src/components/common/SearchField.jsx
  src/components/pages/study/create/CategoryDropdown.jsx
  src/components/pages/study/create/CreateComplete.jsx
  src/components/pages/study/create/ProgressBar.jsx
  src/components/pages/study/create/SearchBook.jsx
  src/components/pages/study/create/StudyForm.jsx
  src/components/pages/study/create/StudyPreview.jsx
  src/pages/study/Create.jsx
Labels: enhancement(개선 요청), P1

#68 ⏬ 게시글 정렬 기능 구현
  src/components/common/DropdownBox.jsx
  src/components/common/Pagination.jsx
  src/components/modules/board/Board.jsx
  src/pages/study/detail/Phrases.jsx
  src/queries/phrases/getPhraseList.js
  src/queries/posts/getPostListByType.js
Labels: enhancement(개선 요청), P2

#78 🐈스터디 홈 오류 및 UX 개선
  src/components/pages/study/home/Filters.jsx
  src/components/pages/study/home/SearchBar.jsx
  src/hooks/useQueryParams.jsx
  src/pages/study/Index.jsx
Labels: bug(버그), enhancement(개선 요청), P1

#79 😸 구절 공유해요 정렬 기능 구현
  src/pages/study/detail/Phrases.jsx
  src/queries/phrases/getPhraseList.js
Labels: enhancement(개선 요청), P2

#81 🫧스터디 홈 모바일 UI 변경
  src/App.css
  src/components/common/BookItem.jsx
  src/components/pages/study/home/Filters.jsx
  src/components/pages/study/home/RecommendedBookSlider.jsx
  src/components/pages/study/home/SearchBar.jsx
  src/components/pages/study/home/SortDropdown.jsx
  src/components/pages/study/home/StudyItem.jsx
  src/pages/study/Index.jsx
  src/pages/study/detail/RecommendedBookSlider.jsx
Labels: bug(버그), enhancement(개선 요청), P1

#82 ✍️ 텍스트 에디터 사용한 게시글 작성, 이미지 삽입 기능 추가
  package-lock.json
  package.json
  src/App.css
  src/assets/icons/icon_plus_white_24.svg
  src/components/common/Editor.jsx
  src/components/modules/board/Board.jsx
  src/components/modules/post/ImageUploadBox.jsx
  src/components/modules/post/PostDetail.jsx
  src/components/modules/post/PostEdit.jsx
  src/components/modules/post/PostWrite.jsx
  src/components/pages/study/detail/StudyInfo.jsx
  src/components/pages/study/detail/StudyMembers.jsx
  src/pages/study/detail/Index.jsx
  src/pages/study/detail/StudyDetailLayout.jsx
  src/queries/phrases/getPhraseList.js
  src/queries/posts/editPost.js
  src/queries/posts/writePost.js
  src/queries/study/getStudyById.js
  src/queries/study/getStudyMemberList.js
Labels: enhancement(개선 요청), P2

#87 🚫 배포 시 발생한 에러 해결 + 오류 페이지 이동 처리
  src/components/common/BookItem.jsx
  src/components/modules/board/Board.jsx
  src/components/pages/study/detail/StudyBook.jsx
  src/components/pages/study/detail/StudyInfo.jsx
  src/components/pages/study/detail/StudyLeader.jsx
  src/components/pages/study/home/StudyNoResults.jsx
  src/hooks/useRequireRole.jsx
  src/pages/SeverError.jsx
  src/pages/Supabase.jsx
  src/pages/Test.jsx
  src/pages/error/Error.jsx
  src/pages/error/NoPermission.jsx
  src/pages/error/NoResults.jsx
  src/pages/error/WrongRequest.jsx
  src/pages/study/detail/Index.jsx
  src/pages/study/detail/Manage.jsx
  src/pages/study/detail/Phrases.jsx
  src/pages/study/detail/RecommendedBookSlider.jsx
  src/pages/study/detail/StudyDetailLayout.jsx
  src/routes/routes.jsx
Labels: bug(버그), enhancement(개선 요청), P3
