Repository chaekggoji/FE, pull requests merged in 2025-03, with the labels that each got.

#11 ✨supabase 초기 세팅 및 api 동작 테스트 resolves #9
  .gitignore
  jsconfig.json
  package-lock.json
  package.json
  src/libs/supabase.js
  src/pages/Supabase.jsx
  src/routes/routes.jsx
  vite.config.js
Labels: enhancement(개선 요청), P2

#16 🔐로그인, 회원가입 페이지 뼈대 작업 resolves #8
  src/assets/icons/icon_no_profile_24.svg
  src/components/common/InterestSelect.jsx
  src/components/layouts/Header.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/routes/routes.jsx
Labels: enhancement(개선 요청), P1

#20 📄기능 별 페이지 생성 및 라우팅 구조 설정 resolves #19
  src/pages/Error.jsx
  src/pages/Guide.jsx
  src/pages/profile/Books.jsx
  src/pages/profile/Edit.jsx
  src/pages/profile/Index.jsx
  src/pages/profile/Studies.jsx
  src/pages/study/Create.jsx
  src/pages/study/Index.jsx
  src/pages/study/detail/Debates.jsx
  src/pages/study/detail/Index.jsx
  src/pages/study/detail/Manage.jsx
  src/pages/study/detail/Notices.jsx
  src/pages/study/detail/Phrases.jsx
  src/routes/ProtectedRoute.jsx
  src/routes/routes.jsx
Labels: enhancement(개선 요청), P1

#24 ✨사이트 이용 소개 페이지 작업 resolves #13
  package-lock.json
  package.json
  src/assets/bookClub.svg
  src/assets/debate.svg
  src/assets/intro.svg
  src/components/common/Button.jsx
  src/index.css
  src/main.jsx
  src/pages/Guide.jsx
  src/pages/auth/Login.jsx
Labels: enhancement(개선 요청), P1

#26 🐛 버튼 디자인 오류, 로그인 이메일 focus: border 색상 원복
  src/components/common/Button.jsx
  src/pages/auth/Login.jsx
Labels: bug(버그)

#27 📖스터디 상세 홈 페이지 1차 마크업, 기타 설정
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/common/BookItem.jsx
  src/components/common/Button.jsx
  src/components/layouts/Footer.jsx
  src/components/layouts/Header.jsx
  src/components/layouts/Index.jsx
  src/components/pages/study/detail/MemberList.jsx
  src/components/pages/study/detail/StudyBook.jsx
  src/components/pages/study/detail/StudyInfo.jsx
  src/components/pages/study/detail/StudyIntro.jsx
  src/components/pages/study/detail/StudyLeader.jsx
  src/components/pages/study/detail/StudyNavLink.jsx
  src/components/pages/study/detail/StudyRules.jsx
  src/pages/auth/Login.jsx
  src/pages/auth/SignUp.jsx
  src/pages/study/Notices.jsx
  src/pages/study/detail/Index.jsx
  src/pages/study/detail/StudyDetailLayout.jsx
  src/routes/ProtectedRoute.jsx
  src/routes/routes.jsx
Labels: enhancement(개선 요청), P1

#31 📝 게시판 페이지 데스크탑 버전 마크업
  src/assets/icons/icon_arrow_up_white_36.svg
  src/assets/icons/icon_more_24.svg
  src/assets/icons/icon_profile_default_36.svg
  src/components/common/Button.jsx
  src/components/common/DropdownBox.jsx
  src/components/common/Pagination.jsx
  src/components/common/SmallDropdownBox.jsx
  src/components/modules/board/Board.jsx
  src/components/modules/board/BoardListItem.jsx
  src/components/modules/board/BoardTitle.jsx
  src/components/modules/post/CommentItem.jsx
  src/components/modules/post/PostDetail.jsx
  src/components/modules/post/PostEdit.jsx
  src/components/modules/post/PostWrite.jsx
  src/hooks/useOutsideClick.jsx
  src/pages/Guide.jsx
  src/pages/study/Notices.jsx
  src/pages/study/detail/Index.jsx
  src/pages/study/detail/Notices.jsx
  src/routes/routes.jsx
Labels: enhancement(개선 요청), P1

#32 ✍️ 스터디 생성 페이지 마크업
  src/assets/icons/icon_arrow_left_24.svg
  src/assets/icons/icon_arrow_right_24.svg
  src/assets/icons/icon_arrow_top_24.svg
  src/assets/icons/icon_check_24.svg
  src/assets/icons/icon_search_24.svg
  src/assets/images/createComplete.svg
  src/components/common/Button.jsx
  src/components/common/CustomInputField.jsx
  src/components/common/CustomTextarea.jsx
  src/components/common/SearchField.jsx
  src/components/layouts/Header.jsx
  src/components/pages/study/create/CategoryDropdown.jsx
  src/components/pages/study/create/CreateComplete.jsx
  src/components/pages/study/create/ProgressBar.jsx
  src/components/pages/study/create/SearchBook.jsx
  src/components/pages/study/create/StudyForm.jsx
  src/components/pages/study/create/StudyPreview.jsx
  src/components/pages/study/detail/StudyInfo.jsx
  src/pages/study/Create.jsx
Labels: enhancement(개선 요청), P1

#35 📖 구절 공유해요, 스터디원 관리 페이지 데스크탑 마크업 완료
  src/components/common/DropdownBox.jsx
  src/components/common/SmallDropdownBox.jsx
  src/components/modules/phrase/PhraseItem.jsx
  src/components/modules/phrase/PhraseWrite.jsx
  src/components/pages/study/detail/StudyInfo.jsx
  src/components/pages/study/detail/StudyMemberListItem.jsx
  src/components/pages/study/detail/StudyMembers.jsx
  src/pages/study/detail/Manage.jsx
  src/pages/study/detail/Phrases.jsx
Labels: enhancement(개선 요청), P1

#38 🐛 스터디 디테일 홈 페이지 import 버그 수정
  src/components/common/SmallDropdownBox.jsx
  src/components/pages/study/detail/StudyInfo.jsx
Labels: bug(버그), P1

#39 🔐회원가입 1차 기능 개발(로그인 x) resolves #17
  jsconfig.json
  src/components/common/InterestSelect.jsx
  src/components/layouts/Header.jsx
  src/pages/auth/SignUp.jsx
  src/routes/routes.jsx
Labels: enhancement(개선 요청), P1

#40 💻 스터디 상세 홈 반응형 완성
  src/App.css
  src/assets/icons/icon_bar_white_24.svg
  src/components/common/BookItem.jsx
  src/components/common/DropdownBox.jsx
  src/components/common/SmallDropdownBox.jsx
  src/components/modules/phrase/PhraseWrite.jsx
  src/components/pages/study/create/CategoryDropdown.jsx
  src/components/pages/study/detail/StudyBook.jsx
  src/components/pages/study/detail/StudyInfo.jsx
  src/components/pages/study/detail/StudyIntro.jsx
  src/components/pages/study/detail/StudyLeader.jsx
  src/components/pages/study/detail/StudyMemberListItem.jsx
  src/components/pages/study/detail/StudyMembers.jsx
  src/components/pages/study/detail/StudyRules.jsx
  src/hooks/useMediaQuery.jsx
  src/hooks/useModalDismiss.jsx
  src/pages/study/detail/FloatNavButton.jsx
  src/pages/study/detail/Index.jsx
  src/pages/study/detail/StudyDetailLayout.jsx
Labels: enhancement(개선 요청), P1

#44 🏠 스터디 홈 레이아웃 작업
  package-lock.json
  package.json
  src/components/pages/study/home/Filters.jsx
  src/components/pages/study/home/Pagination.jsx
  src/components/pages/study/home/SearchBar.jsx
  src/components/pages/study/home/SortDropdown.jsx
  src/components/pages/study/home/StudyItem.jsx
  src/constants/bookSearch.js
  src/pages/Guide.jsx
  src/pages/study/Index.jsx
Labels: enhancement(개선 요청), P1

#47 👀 스터디 생성 페이지 미리보기 반응형 수정
  src/components/common/CustomInputField.jsx
  src/components/common/CustomTextarea.jsx
  src/components/common/SearchField.jsx
  src/components/pages/study/create/SearchBook.jsx
  src/components/pages/study/create/StudyPreview.jsx
  src/components/pages/study/detail/StudyRules.jsx
  src/pages/study/Create.jsx
Labels: enhancement(개선 요청), P2

#45 💻 스터디 공지사항, 토론 게시판 반응형
  src/components/common/DropdownBox.jsx
  src/components/layouts/Header.jsx
  src/components/modules/board/Board.jsx
  src/components/modules/board/BoardListItem.jsx
  src/components/modules/post/CommentItem.jsx
  src/components/modules/post/PostDetail.jsx
  src/components/modules/post/PostEdit.jsx
  src/components/modules/post/PostWrite.jsx
  src/components/pages/study/detail/StudyBook.jsx
  src/components/pages/study/detail/StudyInfo.jsx
  src/pages/study/detail/Debates.jsx
  src/pages/study/detail/FloatNavButton.jsx
  src/pages/study/detail/Manage.jsx
  src/pages/study/detail/Phrases.jsx
Labels: enhancement(개선 요청), P1

#52 🏋️‍♂️ 스터디 디테일 홈 기능 구현
  jsconfig.json
  src/assets/images/book_cover_placeholder.jpg
  src/assets/images/error.png
  src/components/common/BookItem.jsx
  src/components/pages/study/detail/StudyBook.jsx
  src/components/pages/study/detail/StudyInfo.jsx
  src/components/pages/study/detail/StudyIntro.jsx
  src/components/pages/study/detail/StudyLeader.jsx
  src/components/pages/study/detail/StudyMembers.jsx
  src/components/pages/study/detail/StudyRules.jsx
  src/pages/study/detail/Index.jsx
  src/pages/study/detail/StudyDetailLayout.jsx
  src/queries/getStudyById.js
  src/queries/joinStudy.js
  vite.config.js
Labels: enhancement(개선 요청), P1

#53 🥅스터디 홈 반응형
  src/components/pages/study/home/Filters.jsx
  src/components/pages/study/home/SearchBar.jsx
  src/components/pages/study/home/SortDropdown.jsx
  src/components/pages/study/home/StudyItem.jsx
  src/pages/study/Index.jsx
Labels: enhancement(개선 요청), P1

#55 1️⃣ 스터디 게시글 목록 페이지 기능 구현
  src/components/modules/board/Board.jsx
  src/components/modules/board/BoardListItem.jsx
  src/components/modules/post/PostDetail.jsx
  src/components/modules/post/PostEdit.jsx
  src/components/modules/post/PostWrite.jsx
  src/pages/study/detail/StudyDetailLayout.jsx
  src/queries/getPostListByType.js
  src/utils/.gitkeep
  src/utils/time.js
Labels: enhancement(개선 요청), P1
